// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pos/ent/supplier"
	"pos/internal/domain"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SupplierCreate is the builder for creating a Supplier entity.
type SupplierCreate struct {
	config
	mutation *SupplierMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (sc *SupplierCreate) SetName(s string) *SupplierCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetAddress sets the "address" field.
func (sc *SupplierCreate) SetAddress(s string) *SupplierCreate {
	sc.mutation.SetAddress(s)
	return sc
}

// SetEmail sets the "email" field.
func (sc *SupplierCreate) SetEmail(s string) *SupplierCreate {
	sc.mutation.SetEmail(s)
	return sc
}

// SetRepresentative sets the "representative" field.
func (sc *SupplierCreate) SetRepresentative(d domain.Representative) *SupplierCreate {
	sc.mutation.SetRepresentative(d)
	return sc
}

// Mutation returns the SupplierMutation object of the builder.
func (sc *SupplierCreate) Mutation() *SupplierMutation {
	return sc.mutation
}

// Save creates the Supplier in the database.
func (sc *SupplierCreate) Save(ctx context.Context) (*Supplier, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SupplierCreate) SaveX(ctx context.Context) *Supplier {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SupplierCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SupplierCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SupplierCreate) check() error {
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Supplier.name"`)}
	}
	if _, ok := sc.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Supplier.address"`)}
	}
	if _, ok := sc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Supplier.email"`)}
	}
	if _, ok := sc.mutation.Representative(); !ok {
		return &ValidationError{Name: "representative", err: errors.New(`ent: missing required field "Supplier.representative"`)}
	}
	return nil
}

func (sc *SupplierCreate) sqlSave(ctx context.Context) (*Supplier, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SupplierCreate) createSpec() (*Supplier, *sqlgraph.CreateSpec) {
	var (
		_node = &Supplier{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(supplier.Table, sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(supplier.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.Address(); ok {
		_spec.SetField(supplier.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := sc.mutation.Email(); ok {
		_spec.SetField(supplier.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := sc.mutation.Representative(); ok {
		_spec.SetField(supplier.FieldRepresentative, field.TypeJSON, value)
		_node.Representative = value
	}
	return _node, _spec
}

// SupplierCreateBulk is the builder for creating many Supplier entities in bulk.
type SupplierCreateBulk struct {
	config
	builders []*SupplierCreate
}

// Save creates the Supplier entities in the database.
func (scb *SupplierCreateBulk) Save(ctx context.Context) ([]*Supplier, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Supplier, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupplierMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SupplierCreateBulk) SaveX(ctx context.Context) []*Supplier {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SupplierCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SupplierCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
