-- Create "permissions" table
CREATE TABLE `permissions` (`id` bigint NOT NULL AUTO_INCREMENT, `title` varchar(50) NOT NULL, `value` varchar(50) NOT NULL, `group` varchar(50) NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "roles" table
CREATE TABLE `roles` (`id` bigint NOT NULL AUTO_INCREMENT, `create_time` timestamp NOT NULL, `update_time` timestamp NOT NULL, `title` varchar(50) NOT NULL, `value` varchar(50) NOT NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "role_permissions" table
CREATE TABLE `role_permissions` (`role_id` bigint NOT NULL, `permission_id` bigint NOT NULL, PRIMARY KEY (`role_id`, `permission_id`), INDEX `role_permissions_permission_id` (`permission_id`), CONSTRAINT `role_permissions_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `role_permissions_role_id` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "users" table
CREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT, `create_time` timestamp NOT NULL, `update_time` timestamp NOT NULL, `first_name` varchar(50) NOT NULL, `last_name` varchar(50) NOT NULL, `username` varchar(50) NOT NULL, `password` varchar(255) NOT NULL, `phone_number` varchar(255) NULL, `email` varchar(255) NULL, `role_id` bigint NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `username` (`username`), INDEX `users_roles_users` (`role_id`), CONSTRAINT `users_roles_users` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_permissions" table
CREATE TABLE `user_permissions` (`user_id` bigint NOT NULL, `permission_id` bigint NOT NULL, PRIMARY KEY (`user_id`, `permission_id`), INDEX `user_permissions_permission_id` (`permission_id`), CONSTRAINT `user_permissions_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `user_permissions_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
