// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Supplier is the predicate function for supplier builders.
type Supplier func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Vendor is the predicate function for vendor builders.
type Vendor func(*sql.Selector)
